config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :invoice_forms
  resources :invoice_forms
  devise_for :companies
  devise_for :users

  resources :messages do 
    resources :comments
    resources :responses
  end
  root 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :responses
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :find_message, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@messages = Message.all.order("created_at DESC")
	end

	def show
	end

	def new
		@message = current_user.messages.build
	end

	def create
		@message = current_user.messages.build(message_params)
		if @message.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end
	
	def update
		if @message.update(message_params)
			redirect_to message_path
		else
			render 'edit'
		end
	end
	
	def destroy
		@message.destroy
		redirect_to root_path
	end


	private 
		def message_params
			params.require(:message).permit(:title, :description)
		end

		def find_message 
			@message = Message.find(params[:id])
		end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
	<%= f.input :title, label: "Project Title" %>
	<%= f.input :description %>
	<%= f.button :submit %>

<% end %>

app/views/messages/edit.html.erb
<h1>Edit Message</h1>
<%= render 'form' %>

app/views/messages/index.html.erb
<% @messages.each do |message| %> 
	<div class="col-md-4">
		<div class="message">
			<h2 class="message-title"><%= message.title %></h2>
			<%= link_to "View Project", message_path(message), class: "btn-custom" %> 
		</div>

	</div>
<% end %>

app/views/messages/new.html.erb
<div class="col-md-8 col-md-offset-2">

	<h1>New Project</h1>
	<%= render 'form' %>
</div>

app/views/messages/show.html.erb
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
<script>
$(function () {
  $('#switch').change(function () {                
     if($(this).prop("checked")){
	     $('#user_comments').show();
	     $('#company_responses').hide();
     } else{
	     $('#user_comments').hide();
	     $('#company_responses').show();
     }
  }); 
});
</script>
</head>

<input type="checkbox" data-on-text="" data-off-text="" data-role="flipswitch" name="switch" id="switch">
<div class="col-md-8 col-md-offset-2">
	<div class="message-show">
		<h2><%= @message.title %></h2>
		<p class="message-posted-by">Posted by <%= @message.user.email %> <%= time_ago_in_words(@message.created_at) %> ago</p>
		<p class="message-description"><%= @message.description %></p>

		    <div id="user_comments">
				<h3>Comments:</h3>
				<%= render @message.comments %>
				<h3 class="reply-to-msg">Reply to the Project:</h3>
				<%= render 'comments/form' %>
			</div>				
			
			<div id="company_responses">
				<h3>Company Responses:</h3>
				<%= render @message.responses %> 
				<h3 class="reply-to-msg">Reply to the Project:</h3>
				<%= render 'responses/form' %>
			</div>

		<div class="links btn-group">
			<%= link_to "Back", root_path, class: "btn btn-default" %>
			<% if  user_signed_in? %>
				<% if @message.user_id == current_user.id %>
					<%= link_to "Edit", edit_message_path(@message), class: "btn btn-default"  %>
					<%= link_to "Delete", message_path(@message), method: :delete, data: {confirm: "Are you sure you want to delete this project?"}, class: "btn btn-default"  %>
				<% end %>
			<% end %>
		</div>
	</div>
</div>