config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :invoice_forms
  resources :invoice_forms
  devise_for :companies
  devise_for :users

  resources :messages do 
    resources :comments
    resources :responses
  end
  root 'messages#index'
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
	has_many :fields, class_name: "InvoiceField"
	accepts_nested_attributes_for :fields, allow_destroy: true 
end

app/models/invoice_form.rb
class InvoiceForm < ActiveRecord::Base
	has_many :invoice_fields, :dependent => :destroy
	accepts_nested_attributes_for :invoice_fields, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.all
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:name, :fields_attributes)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_field_fields.html.erb
<fieldset>
	<%= f.select :field_type, %w[text_field check_box] %>
	<%= f.text_field :name, placeholder: "field_name"  %>
	<%= f.check_box :required  %> <%= f.label :required  %>
	<%= f.hidden_field :_destroy %>
	<%= link_to "[remove]", '#', class: "remove_fields" %>
</fieldset>

app/views/invoices/_form.html.erb
<%= simple_form_for(@invoice) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <%= f.fields_for :fields do |builder| %>
  	<%= render 'field_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Line Item", f, :fields %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css">
<script src="http://code.jquery.com/jquery-1.11.3.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"></script>
</head>
<body>

<p id="notice"><%= notice %></p>

<h1>Listing Invoices</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.name %></td>
        <td><%= link_to 'Show', invoice %></td> <br />
        <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
        <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<%= link_to 'Back', invoices_path %>
<br>
<img src="/images/invoice.JPG" alt="rss feed" />

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice.name %>
</p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>