config/routes.rb
Rails.application.routes.draw do
  resources :invoices
  resources :invoice_forms
  resources :invoice_forms
  devise_for :companies
  devise_for :users

  resources :messages do 
    resources :comments
    resources :responses
  end
  root 'messages#index'
end

app/controllers/invoice_forms_controller.rb
class InvoiceFormsController < ApplicationController
  before_action :set_invoice_form, only: [:show, :edit, :update, :destroy]

  # GET /invoice_forms
  # GET /invoice_forms.json
  def index
    @invoice_forms = InvoiceForm.all
  end

  # GET /invoice_forms/1
  # GET /invoice_forms/1.json
  def show
  end

  # GET /invoice_forms/new
  def new
    @invoice_form = InvoiceForm.new
  end

  # GET /invoice_forms/1/edit
  def edit
  end

  # POST /invoice_forms
  # POST /invoice_forms.json
  def create
    @invoice_form = InvoiceForm.new(invoice_form_params)

    respond_to do |format|
      if @invoice_form.save
        format.html { redirect_to @invoice_form, notice: 'Invoice form was successfully created.' }
        format.json { render :show, status: :created, location: @invoice_form }
      else
        format.html { render :new }
        format.json { render json: @invoice_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoice_forms/1
  # PATCH/PUT /invoice_forms/1.json
  def update
    respond_to do |format|
      if @invoice_form.update(invoice_form_params)
        format.html { redirect_to @invoice_form, notice: 'Invoice form was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice_form }
      else
        format.html { render :edit }
        format.json { render json: @invoice_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoice_forms/1
  # DELETE /invoice_forms/1.json
  def destroy
    @invoice_form.destroy
    respond_to do |format|
      format.html { redirect_to invoice_forms_url, notice: 'Invoice form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice_form
      @invoice_form = InvoiceForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_form_params
      params.require(:invoice_form).permit(:name)
    end
end

app/helpers/invoice_forms_helper.rb
module InvoiceFormsHelper
end

app/views/invoice_forms/_form.html.erb
<%= simple_form_for(@invoice_form) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Project Name" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/invoice_forms/edit.html.erb
<h1>Editing Invoice Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice_form %> |
<%= link_to 'Back', invoice_forms_path %>

app/views/invoice_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Invoice Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @invoice_forms.each do |invoice_form| %>
      <tr>
        <td><%= invoice_form.name %></td> 
        <td><%= link_to 'Show', invoice_form %></td>
        <td><%= link_to 'Edit', edit_invoice_form_path(invoice_form) %></td>
        <td><%= link_to 'Destroy', invoice_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice form', new_invoice_form_path %>

app/views/invoice_forms/new.html.erb
<h1>New Invoice Form</h1>

<%= render 'form' %>

<%= link_to 'Back', invoice_forms_path %>

app/views/invoice_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @invoice_form.name %>
</p>

<ol>
<% for invoice_field in @invoice_form.invoice_fields %>
	<li><%=h invoice_field.description %></li>
<% end %>
</ol>

<%= link_to 'Edit', edit_invoice_form_path(@invoice_form) %> |
<%= link_to 'Delete', @survey, :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', invoice_forms_path %>